### ISSUE TITLE
Docker Hub build does not start on newly pushed GitHub tag

### ISSUE THREAD

**Issue by ximon18** [docker/hub-feedback#1765]
## Problem description
Automated build on Docker Hub does not start when a new tag is pushed to GitHub, even though the GitHub webhook created by Docker Hub exists and shows it was executed.

Builds invoked manually by pressing **"Save and Build"** work as expected.

I have tried unlinking and relinking the Docker Hub repository with the GitHub repository.
I have tried different build rule settings.
I have tried pushing different tags to GitHub (only plain tags, not annotated tags).

GitHub Ping **does** show up in the Docker Hub timeline, but other GitHub web hook activity does not.

I tried Googling for about an hour and reading various articles but did not find anything that helped.

## Docker Hub configuration
At https://cloud.docker.com/u/nlnetlabs/repository/docker/nlnetlabs/pythonunbound/builds, I have tried various different "Source" patterns, including `FIXED_STRING`, `/^v[0-9.]+$/`, `/[0-9.]+/`, and more. I also tried using a `FIXED_STRING` for `Docker Tag`.

- **SOURCE REPOSITORY:** `ximon18` `pythonunbound`
- **BUILD LOCATION:** `Build on Docker Hub's infrastructure`
- **AUTOTEST:** `Off`
- **REPOSITORY LINKS:** `Off`
- **BUILD RULES:**
-- **Source Type:** `Tag`
-- **Source:** `/v[0-9.]+$/`
-- **Docker Tag:** `{sourceref}`
-- **Dockerfile location:** `Dockerfile`
-- **Build Context:** `/`
-- **Autobuild:** ON
-- **Build Caching:** ON

## GitHub configuration
Docker Hub created the following webhook in my Github project admin settings when I linked my personal GitHub account with Docker Hub: _(I deliberately did not include my UUID when pasting the Payload URL here)_

- **Payload URL:**  `https://cloud.docker.com/api/build/v1/vcs/<UUID>/trigger/call/`
- **Content type:** `application/json`
- **Secret:** ``
- **SSL verification:** `Enable SSL verification`
- **Which events would you like to trigger this webhook:** `Let me select individual events`
-- _Pushes_
-- _Pull requests_

## GitHub webhook invocation history
I can see that the hook has fired, e.g.

TICK  955f7e98-4401-11e9-928c-48e0c6231454 2019-03-11 14:28:40
**Headers:**
```
Request URL: https://cloud.docker.com/api/build/v1/vcs/<UUID>/trigger/call/
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/123faed
X-GitHub-Delivery: 955f7e98-4401-11e9-928c-48e0c6231454
X-GitHub-Event: push
```
**Payload:**
```
{
  "ref": "refs/tags/v0.0.0",
  "before": "0000000000000000000000000000000000000000",
  "after": "8651e790a6b619cd07b6a2a616cc366e7200c96e",
  "created": true,
  "deleted": false,
  "forced": false,
  "base_ref": "refs/heads/master",
  "compare": "https://github.com/ximon18/pythonunbound/compare/v0.0.0",
  "commits": [

  ],
  "head_commit": {
    "id": "8651e790a6b619cd07b6a2a616cc366e7200c96e",
    "tree_id": "3987b2171b6c5af5d380833b85916ff0199b5cca",
    "distinct": true,
    "message": "Noted how to build a different version of Unbound.",
    "timestamp": "2019-03-08T22:27:37+01:00",
    "url": "https://github.com/ximon18/pythonunbound/commit/8651e790a6b619cd07b6a2a616cc366e7200c96e",
    "author": {
      "name": "ximon18",
      "email": "3304436+ximon18@users.noreply.github.com",
      "username": "ximon18"
    },
    "committer": {
      "name": "GitHub",
      "email": "noreply@github.com",
      "username": "web-flow"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "README.md"
    ]
  },
  "repository": {
    "id": 174546472,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNzQ1NDY0NzI=",
    "name": "pythonunbound",
    "full_name": "ximon18/pythonunbound",
    "private": false,
    "owner": {
      "name": "ximon18",
      "email": "3304436+ximon18@users.noreply.github.com",
      "login": "ximon18",
      "id": 3304436,
      "node_id": "MDQ6VXNlcjMzMDQ0MzY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3304436?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ximon18",
      "html_url": "https://github.com/ximon18",
      "followers_url": "https://api.github.com/users/ximon18/followers",
      "following_url": "https://api.github.com/users/ximon18/following{/other_user}",
      "gists_url": "https://api.github.com/users/ximon18/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ximon18/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ximon18/subscriptions",
      "organizations_url": "https://api.github.com/users/ximon18/orgs",
      "repos_url": "https://api.github.com/users/ximon18/repos",
      "events_url": "https://api.github.com/users/ximon18/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ximon18/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/ximon18/pythonunbound",
    "description": "A simple Dockerfile that builds Unbound 1.9.0 --with-pythonmodule support and includes a simple Hello World style Python # module to demonstrate the --with-pythonmodule functionality.",
    "fork": false,
    "url": "https://github.com/ximon18/pythonunbound",
    "forks_url": "https://api.github.com/repos/ximon18/pythonunbound/forks",
    "keys_url": "https://api.github.com/repos/ximon18/pythonunbound/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/ximon18/pythonunbound/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/ximon18/pythonunbound/teams",
    "hooks_url": "https://api.github.com/repos/ximon18/pythonunbound/hooks",
    "issue_events_url": "https://api.github.com/repos/ximon18/pythonunbound/issues/events{/number}",
    "events_url": "https://api.github.com/repos/ximon18/pythonunbound/events",
    "assignees_url": "https://api.github.com/repos/ximon18/pythonunbound/assignees{/user}",
    "branches_url": "https://api.github.com/repos/ximon18/pythonunbound/branches{/branch}",
    "tags_url": "https://api.github.com/repos/ximon18/pythonunbound/tags",
    "blobs_url": "https://api.github.com/repos/ximon18/pythonunbound/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/ximon18/pythonunbound/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/ximon18/pythonunbound/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/ximon18/pythonunbound/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/ximon18/pythonunbound/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/ximon18/pythonunbound/languages",
    "stargazers_url": "https://api.github.com/repos/ximon18/pythonunbound/stargazers",
    "contributors_url": "https://api.github.com/repos/ximon18/pythonunbound/contributors",
    "subscribers_url": "https://api.github.com/repos/ximon18/pythonunbound/subscribers",
    "subscription_url": "https://api.github.com/repos/ximon18/pythonunbound/subscription",
    "commits_url": "https://api.github.com/repos/ximon18/pythonunbound/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/ximon18/pythonunbound/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/ximon18/pythonunbound/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/ximon18/pythonunbound/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/ximon18/pythonunbound/contents/{+path}",
    "compare_url": "https://api.github.com/repos/ximon18/pythonunbound/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/ximon18/pythonunbound/merges",
    "archive_url": "https://api.github.com/repos/ximon18/pythonunbound/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/ximon18/pythonunbound/downloads",
    "issues_url": "https://api.github.com/repos/ximon18/pythonunbound/issues{/number}",
    "pulls_url": "https://api.github.com/repos/ximon18/pythonunbound/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/ximon18/pythonunbound/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/ximon18/pythonunbound/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/ximon18/pythonunbound/labels{/name}",
    "releases_url": "https://api.github.com/repos/ximon18/pythonunbound/releases{/id}",
    "deployments_url": "https://api.github.com/repos/ximon18/pythonunbound/deployments",
    "created_at": 1552053356,
    "updated_at": "2019-03-08T21:27:39Z",
    "pushed_at": 1552310920,
    "git_url": "git://github.com/ximon18/pythonunbound.git",
    "ssh_url": "git@github.com:ximon18/pythonunbound.git",
    "clone_url": "https://github.com/ximon18/pythonunbound.git",
    "svn_url": "https://github.com/ximon18/pythonunbound",
    "homepage": null,
    "size": 9,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Dockerfile",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master"
  },
  "pusher": {
    "name": "ximon18",
    "email": "3304436+ximon18@users.noreply.github.com"
  },
  "sender": {
    "login": "ximon18",
    "id": 3304436,
    "node_id": "MDQ6VXNlcjMzMDQ0MzY=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/3304436?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ximon18",
    "html_url": "https://github.com/ximon18",
    "followers_url": "https://api.github.com/users/ximon18/followers",
    "following_url": "https://api.github.com/users/ximon18/following{/other_user}",
    "gists_url": "https://api.github.com/users/ximon18/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ximon18/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ximon18/subscriptions",
    "organizations_url": "https://api.github.com/users/ximon18/orgs",
    "repos_url": "https://api.github.com/users/ximon18/repos",
    "events_url": "https://api.github.com/users/ximon18/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ximon18/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

## Docker Hub timeline ##
Only "Github" ping events appear, caused linking Docker Hub to GitHub.

**Comment by JPZ13** [comment]
Hi @ximon18 . I'm J.P., and I work on the Docker Hub team. Thank you for providing all of the troubleshooting information. Looking at your Github repo [here](https://github.com/ximon18/pythonunbound/commits/master), I can see that the most recent tag was made three days ago and kicked off a successful build. My screenshot is below. Can you try pushing another tag and reporting what the output is?
<img width="894" alt="Screen Shot 2019-03-11 at 1 31 02 PM" src="https://user-images.githubusercontent.com/6625432/54155900-4af98280-4402-11e9-9e9b-c951da75ba69.png">

**Comment by ximon18** [comment]
Hi,

I will push another tag tomorrow.

I pushed several tags earlier today but have since deleted them after
seeing no reaction from Docker hub to the pushed tags. That is why the last
tag appears to be from 3 days ago.

Thanks,

Ximon

**Comment by ximon18** [comment]
Also, the tagged image in Docker Hub was, if I recall correctly, pushed to
Docker manually, not built by Docker Hub in response to a GitHub webhook
trigger.

Ximon

**Comment by ximon18** [comment]
Good morning,
I have pushed a commit to master and tagged it this morning and I see both master and tag builds initiated at Docker Hub.
Is it possible that the issue was caused by tagging a commit that was already built by Docker Hub and is thus silently ignored?
Thanks,
Ximon

**Comment by JPZ13** [comment]
@ximon18 Glad it's working. It's possible, and I will look into it.

**Comment by ximon18** [comment]
Good morning,

I'm afraid this problem appears to be back. Yesterday we pushed to master in our GitHub repo and Docker Hub correctly started a build, but when a GitHub tag was created the tag build was not started by Docker Hub.

**Details:**
Docker Hub repository: https://hub.docker.com/r/nlnetlabs/internetnl
Linked GutHub repository: https://github.com/NLnetLabs/Internet.nl
Docker Hub Automated Build configuration:

Docker Tag | Source      | Build Status | Autobuild | Build caching
---------- | ----------- | ------------ | --------- | -------------
latest     | master      | SUCCESS      | YES       | YES
{sourceref}| /^v[0-9.]+/ | EMPTY        | YES       | YES

GitHub Tag details:
![image](https://user-images.githubusercontent.com/3304436/54984863-0ba96500-4fb0-11e9-8873-e5f576c4eb3a.png)

Docker Hub build history:
![image](https://user-images.githubusercontent.com/3304436/54984941-309dd800-4fb0-11e9-937f-8dee919f0f40.png)

As you can see there was no build for tag v1.0.3.

Thanks,

Ximon

**Comment by meticulous-dft** [comment]
Hey, it looks like there is an empty space in the rules `source_name: " /^v[0-9.]+/"`, which is not matching any tags. 

I think it will work once you remove the empty space. Also you should see `{\1}` instead of `{sourceref}` if regex rule match is correct. Let me know if this solves the problem.


We will add the strip in UI to make sure prevent this.

**Comment by ximon18** [comment]
> Hey, it looks like there is an empty space in the rules source_name: " /^v[0-9.]+/", which is not matching any tags.

Aahhh! I didn't see that! Thx! I don't plan on pushing a new tag just yet, I'll post back here next time I do to update if the problem is fixed (I assume it is) or not.

**Comment by fwilhe** [comment]
I face a similar issue. We want to build `master` (which works) and tags (in the format `v12`) which does not work. I think it broke with the relaunch of Docker hub, it used to work before.

This is our old configuration, which used to work up until January 2019. Why is the tag 'empty' now?

![image](https://user-images.githubusercontent.com/2292245/55551270-b15c8280-56da-11e9-8e89-d694c478e5d1.png)

I've tried all combinations of regex I can think of, also quite similar to what you provide in the examples (`/^v([0-9.]+)$/`, `/^v([0-9]+)$/`), but nothing changes, the tag is always empty. If I hardcode one particular tag (so `v16` instead of any regex), the build works. But of course this is no solution.

What can I do to find out more about the issue? I don't see why the regex should not match, it is a wildcard.

**Comment by meticulous-dft** [comment]
Empty means the build is never triggered from this rule. Can you remove the current one, and create a new one with the regex similar to the examples to see if it works?

**Comment by fwilhe** [comment]
Hi @meticulous-dft,

all right, I was expecting to be able to trigger building of (unbuilt, but old) GitHub tags with this rule. When pushing, it does actually work.

I'm not happy with the UX of DockerHub, the state of things is in many places not good visible, but at least the issue we had seems resolved now. Thanks.

**Comment by meticulous-dft** [comment]
Thanks for letting me know. The UX unfortunately is far from great. We are working on to improve it.

**Comment by brugnara** [comment]
> Thanks for letting me know. The UX unfortunately is far from great. We are working on to improve it.

Maybe an input where you can type in the tag to build, in order to be able to replicate the `push` command should be enough?

Thanks @fwilhe since your comment gave me the solution: re-pushing tag for triggering a new build :muscle:

**Comment by fwilhe** [comment]
Again our automated builds stopped building tags out of the blue. `latest` (git `master`) still works, git tags like `v42` don't trigger. @meticulous-dft Any suggestions for how to resolve?

**Comment by Guang1234567** [comment]
Still not work in 2010-08-12 -_-||,  i think create a `demo-hello-world-docker` project can reproduce the problem.

My cfg:

![image](https://user-images.githubusercontent.com/8240718/90491452-85785a80-e172-11ea-9c23-940f2b77d700.png)

I already test in [regex101.com](https://regex101.com/r/hYMvKp/1/), it ( `\^v([0-9.]+$)\` ) works,  but in docker-hub donot trigger auto-build

![image](https://user-images.githubusercontent.com/8240718/90492573-eb191680-e173-11ea-85d1-01bc0d90f15d.png)


thanks.

**Comment by oerp-odoo** [comment]
For me auto build was triggering on tag push previously, but suddenly stopped working. Tag format has not changed nor regex pattern was changed on docker hub. Seems it just ignoring it now.
