### ISSUE TITLE
"Link Github" apparently broken.

### ISSUE THREAD

**Issue by patsplat** [docker/hub-feedback#534]
1. Browsed to Profile -> Settings -> Linked Accounts & Services
2. Clicked "Link Github"
3. Selected "Public & Private"

In a new window am able to login (via two-factor authentication) and approve the connection.  Window closes and Docker Hub displays the attached error:

![screen shot 2016-01-06 at 2 44 54 pm](https://cloud.githubusercontent.com/assets/178626/12152726/1535f70c-b484-11e5-97ba-6f706e44fa0f.png)

This account should not be associated with any other docker hub accounts.

p.s. Though non-functional the link does appear to be present in github:

![screen shot 2016-01-06 at 2 45 52 pm](https://cloud.githubusercontent.com/assets/178626/12152768/548f4dd6-b484-11e5-9f0c-f350e9098b31.png)

**Comment by nhsiehgit** [comment]
hi @patsplat 

Thanks for the issue. Can you confirm that the account has actually been connected? (refresh the page or attempt to create automated build)

**Comment by patsplat** [comment]
The connection isn't visible on the docker hub side

**Comment by akshayvyas** [comment]
@patsplat, can you revoke the Docker Hub Registry from Github and try to relink the account from Docker Hub?  We released a new version of Docker Hub yesterday.

**Comment by nhsiehgit** [comment]
hi @patsplat - Sorry for the multiple (and late) pings,

We've recently deployed some changes to the hub. Please try again and let us know if you're still encountering the same issue! We've noticed that there's possibly some caching going on in the browser so if you can't link on the first attempt, see if linking in an incognito window works.

Let us know if this solves your issue!

**Comment by patsplat** [comment]
Apologies for the delay am launching a project. Will test this out soon and
thanks for the investigation!

**Comment by DDN-Shep** [comment]
I have the same problem and still have this problem (I've tried revoking the OAuth rights on GitHub for DockerHub and trying again several times, no luck).

This has been a problem for months now...
(BitBucket worked though)

**Comment by DDN-Shep** [comment]
This still happens for me ...will raise another issue, because this was closed prematurely
