### ISSUE TITLE
Automated build upon git push not working on Docker Hub

### ISSUE THREAD

**Issue by alvinypyim** [docker/hub-feedback#978]
Automated build upon git push stopped working on Docker Hub since about 6 hours ago.

Could the support team of Docker Hub follow it up, thanks?

**Comment by oskarsvard** [comment]
I have the same problem since friday afternoon. Get "Request status: NET_ERR" from the webhook response in bitbucket.

Thanks,
Oskar

**Comment by mikecouk** [comment]
Yep we're getting the same, also affects Bitbucket, and manual triggering of builds via CURL etc. This is a big problem by the sounds of it !

**Comment by madwire** [comment]
Same here!

**Comment by pkennedyr** [comment]
Thank you for the feedback. We are investigating the issue and will post an update as soon as more information is available.

**Comment by afindlator** [comment]
Automated builds are broken form bitbucket as well

**Comment by pkennedyr** [comment]
**UPDATE**:  As of 1:05pm (PDT), this issue is no longer appearing after an upstream fix was deployed by Bitbucket. We apologize for the inconvenience and please let us know if you experience issues in the future.

**Comment by oskarsvard** [comment]
Great work! Thanks a lot! :)

**Comment by alvinypyim** [comment]
Thanks @pkennedyr!

**Comment by jmandrade** [comment]
Still having problems with automated builds (Jenkins): `unauthorized: authentication required`

**Comment by pkennedyr** [comment]
@jmandrade Can you open a separate ticket with the specifics of your issue? The Bitbucket issue described on this thread appears to have been resolved.

**Comment by jmandrade** [comment]
@pkennedyr sure thing!
